version: '3.8'

services:
  scoreboard-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scoreboard-app
    restart: unless-stopped
    ports:
      - "3443:3000"  # Map container port 3000 to host port 3001
    networks:
      - scoreboard-network
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0

networks:
  scoreboard-network:
    driver: bridge